import { ACCOUNTS, EXPENSES, INCOME, COLORS, money, summary, categoryTotals, monthLabel, shiftMonth } from './finance.js';

export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
  grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
  list:'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',
  wallet:'M20 8V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v12H5a3 3 0 0 1-3-3V6m18 7h-5v4h5',
  chart:'M4 20V10m8 10V4m8 16v-7',
  settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
  plus:'M12 5v14M5 12h14', left:'m14 6-6 6 6 6', right:'m10 6 6 6-6 6',
  down:'M12 4v16m-6-6 6 6 6-6', up:'M12 20V4m-6 6 6-6 6 6',
  search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',
  edit:'m16 3 5 5-12 12-6 1 1-6z M14 5l5 5', close:'m6 6 12 12M6 18 18 6',
  cloud:'M6 19a5 5 0 1 1 0-10 7 7 0 0 1 13-2 6 6 0 0 1 0 12',
  logout:'M9 3H3v18h6M10 12h11m-5-5 5 5-5 5', check:'m5 12 4 4L19 6',
  target:'M22 12a10 10 0 1 1-10-10m0 5a5 5 0 1 0 5 5m-5 0L22 2m-5 0h5v5',
  coffee:'M4 8h12v9a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4z M16 9h2a3 3 0 0 1 0 6h-2M7 2v2m5-2v2',
  bag:'M4 7h16l1 14H3z M8 8V6a4 4 0 0 1 8 0v2', home:'m3 10 9-8 9 8v11H3z M9 21v-9h6v9',
  card:'M2 5h20v14H2z M2 9h20M6 15h3', heart:'M12 21 3 12A6 6 0 0 1 12 4a6 6 0 0 1 9 8z',
  download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5', refresh:'M20 7V2m0 5h-5M4 17v5m0-5h5M5 7a8 8 0 0 1 15 0M4 17a8 8 0 0 0 15 0'
};
export function icon(name,cls='') { return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.wallet}"/></svg>`; }
export function categoryIcon(category) { return ({'Food & drinks':'coffee','Groceries':'bag','Shopping':'bag','Housing':'home','Health':'heart','Salary':'wallet','Transport':'card'})[category] || 'wallet'; }
export function categoryColor(category) { return COLORS[Math.max(0,EXPENSES.indexOf(category))]; }
const button = (action,text,cls='secondary',ico='') => `<button class="button ${cls}" data-action="${action}">${ico ? icon(ico) : ''}${text}</button>`;
export function shell(state) {
  const titles = {overview:['YOUR MONEY, IN FOCUS','Monthly overview'],transactions:['THE EVERYDAY DETAILS','Transactions'],budgets:['MAKE ROOM FOR WHAT MATTERS','Monthly budgets'],reports:['SEE THE BIGGER PICTURE','Spending reports'],settings:['MAKE IT YOURS','Settings & data']};
  const [eyebrow,title] = titles[state.page];
  return `<aside class="sidebar"><a class="brand" href="#overview" aria-label="Pocketwise home"><span class="brand-mark">p<span>·</span></span>Pocketwise<span class="brand-dot">.</span></a>
    <div class="nav-label">WORKSPACE</div><nav aria-label="Main navigation">${[['overview','grid','Overview'],['transactions','list','Transactions'],['budgets','target','Budgets'],['reports','chart','Reports']].map(([page,ico,text])=>`<a href="#${page}" class="nav-link ${state.page===page?'active':''}" ${state.page===page?'aria-current="page"':''}>${icon(ico)}<span>${text}</span>${state.page===page?'<span class="active-dot"></span>':''}</a>`).join('')}</nav>
    <div class="sidebar-tip">${icon('wallet')}<strong>Small steps.<br>More peace of mind.</strong><p>A little check-in today goes a long way.</p></div>
    <div class="sidebar-bottom"><a href="#settings" class="nav-link ${state.page==='settings'?'active':''}">${icon('settings')}<span>Settings & data</span></a><div class="profile"><span class="avatar">${state.demo?'D':escape(state.user?.email?.[0]?.toUpperCase() || 'P')}</span><div><strong>${state.demo?'Demo workspace':'Personal workspace'}</strong><span title="${escape(state.user?.email)}">${state.demo?'Explore with sample data':escape(state.user?.email || 'Sign in to sync')}</span></div></div></div></aside>
    <main><header class="page-header"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div><div class="header-actions">${state.page!=='settings'?`<div class="month-picker"><button class="icon-button" data-action="prev-month" aria-label="Previous month">${icon('left')}</button><label><span class="sr-only">Selected month</span><input type="month" id="month-picker" min="1900-01" max="2200-12" value="${state.month}" /></label><button class="icon-button" data-action="next-month" aria-label="Next month">${icon('right')}</button></div>`:''}${button('add','Add transaction','primary','plus')}</div></header>
    ${state.demo?`<div class="demo-banner"><span>${icon('cloud')}<strong>Demo mode</strong> <span>Sample data. Changes last until you reload.</span></span>${button('login','Sign in to save & sync','text-button','right')}</div>`:`<div class="sync-line"><span>${icon('cloud')}${state.loading?'Loading your records…':state.loadError?'Sync needs attention':`Saved to your account · ${state.currency}`}</span>${button('refresh','Refresh','text-button','refresh')}</div>`}
    ${state.loadError?`<div class="error-banner" role="alert">${escape(state.loadError)} Please check your connection and try Refresh.</div>`:''}
    <div id="page-content">${!state.ready&&!state.demo?'<div class="empty-state"><h2>Your workspace is loading</h2><p>Your records will appear once the connection is ready.</p></div>':page(state)}</div>
    <footer class="page-footer"><span>Pocketwise <span class="muted">/</span> A clearer picture of your money.</span><span>${state.currency} · ${state.demo?'Sample workspace':'Personal finance'}</span></footer></main>`;
}
function page(s) { return ({overview,transactions,budgets,reports,settings})[s.page](s); }
export function transactionRows(rows,s,compact=false) {
  if (!rows.length) return `<div class="empty-state">${icon('list')}<h3>No transactions here yet</h3><p>Add an income or expense to start your money story.</p>${button('add','Add transaction','primary','plus')}</div>`;
  return `<div class="table-scroll"><table><thead><tr><th>Transaction</th><th>Date</th>${!compact?'<th>Account</th>':''}<th class="align-right">Amount</th><th><span class="sr-only">Edit</span></th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="transaction-name"><span class="category-icon" style="--category:${categoryColor(r.category)}">${icon(categoryIcon(r.category))}</span><span><strong>${escape(r.note || r.category)}</strong><small>${escape(r.category)}</small></span></div></td><td class="date-cell">${new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(r.date+'T12:00:00Z'))}</td>${!compact?`<td><span class="account-tag">${escape(r.account)}</span></td>`:''}<td class="align-right amount ${r.type==='income'?'positive':''}">${r.type==='income'?'+':'−'}${money(r.amount,s.currency)}</td><td><button class="icon-button" data-action="edit" data-id="${escape(r.id)}" aria-label="Edit ${escape(r.note || r.category)}">${icon('edit')}</button></td></tr>`).join('')}</tbody></table></div>`;
}
function overview(s) {
  const sum=summary(s.transactions,s.month), limits=s.budgets.filter(b=>b.month===s.month), total=limits.reduce((a,b)=>a+b.amount,0), remaining=total-sum.expenses;
  const rows=s.transactions.filter(t=>t.date.startsWith(s.month)).sort((a,b)=>b.date.localeCompare(a.date));
  return `<section class="stats" aria-label="Monthly summary"><article class="stat-card balance-card"><div class="stat-label">Money left this month${icon('wallet')}</div><div class="stat-value">${money(sum.net,s.currency)}</div><div class="stat-foot">Income minus expenses <span>${s.currency}</span></div></article><article class="stat-card"><div class="stat-label">Income<span class="mini-icon income">${icon('down')}</span></div><div class="stat-value">${money(sum.income,s.currency)}</div><div class="stat-foot">${rows.filter(r=>r.type==='income').length} income transactions</div></article><article class="stat-card"><div class="stat-label">Expenses<span class="mini-icon expense">${icon('up')}</span></div><div class="stat-value">${money(sum.expenses,s.currency)}</div><div class="stat-foot">${rows.filter(r=>r.type==='expense').length} expense transactions</div></article><article class="stat-card"><div class="stat-label">Budget remaining<span class="mini-icon budget">${icon('target')}</span></div><div class="stat-value ${total&&remaining<0?'negative':''}">${total?money(remaining,s.currency):'—'}</div><div class="stat-foot">${total?`${money(total,s.currency)} total monthly limit`:'Set your first monthly budget'}</div></article></section>
    <div class="overview-grid"><section class="panel spending-panel"><div class="panel-heading"><div><h2>Where your money goes</h2><p>Expenses by category</p></div><span class="tag">${monthLabel(s.month,true)}</span></div>${spending(s)}</section><section class="panel"><div class="panel-heading"><div><h2>Budget check-in</h2><p>A plan for the everyday</p></div><a href="#budgets" class="subtle-link">View all ${icon('right')}</a></div>${budgetBars(s,4)}<div class="panel-note">${icon('target')}${total?remaining>=0?`${money(remaining,s.currency)} left across your total budget.`:`${money(-remaining,s.currency)} above your total budget.`:'Give each category a limit that works for you.'}</div></section></div>
    <section class="panel recent"><div class="panel-heading"><div><h2>Recent transactions</h2><p>Your latest ins and outs</p></div><a href="#transactions" class="subtle-link">View all transactions ${icon('right')}</a></div>${transactionRows(rows.slice(0,6),s,true)}</section>`;
}
function spending(s) {
  const values=Object.entries(categoryTotals(s.transactions,s.month)).sort((a,b)=>b[1]-a[1]);
  const total=values.reduce((a,[,n])=>a+n,0);
  let start=0;
  const stops=values.map(([c,n])=>{ const end=start+n/total*100; const stop=`${categoryColor(c)} ${start}% ${end}%`;start=end;return stop; }).join(',');
  return `<div class="spending-content"><div class="donut" style="background:${total?`conic-gradient(${stops})`:'#edf0f6'}" role="img" aria-label="Category spending. Total ${money(total,s.currency)}. Details alongside."><div><small>Total spent</small><strong>${money(total,s.currency)}</strong><span>${s.currency}</span></div></div><div class="legend">${values.length?values.map(([c,n])=>`<div class="legend-row"><span class="legend-dot" style="background:${categoryColor(c)}"></span><span>${escape(c)}<small>${Math.round(n/total*100)}% of expenses</small></span><strong>${money(n,s.currency)}</strong></div>`).join(''):'<p class="muted">Your spending breakdown will appear after your first expense.</p>'}</div></div>`;
}
function budgetBars(s,limit=99) {
  const totals=categoryTotals(s.transactions,s.month), rows=s.budgets.filter(b=>b.month===s.month);
  if (!rows.length) return `<div class="empty-state compact">${icon('target')}<h3>A fresh month, a fresh plan</h3><p>Set a limit for groceries, bills, and the little things.</p>${button('budget-edit','Set monthly budgets','primary')}</div>`;
  return `<div class="budget-bars">${rows.slice(0,limit).map(b=>{const spent=totals[b.category]||0,pct=spent/b.amount*100;return `<div class="budget-bar"><div><strong>${escape(b.category)}</strong><span><b>${money(spent,s.currency)}</b> / ${money(b.amount,s.currency)}</span></div><progress max="${b.amount}" value="${Math.min(spent,b.amount)}" class="${pct>100?'over':''}" aria-label="${escape(b.category)}: ${Math.round(pct)}% of budget"></progress><small class="${pct>100?'negative':'muted'}">${pct>100?`${money(spent-b.amount,s.currency)} over budget`:`${money(b.amount-spent,s.currency)} remaining`}</small></div>`;}).join('')}</div>`;
}
export function filteredTransactions(s) { return s.transactions.filter(r=>r.date.startsWith(s.month) && (s.filter==='all'||r.type===s.filter) && (s.category==='all'||r.category===s.category) && `${r.note} ${r.category} ${r.account} ${r.date}`.toLowerCase().includes(s.search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)); }
export function transactionResults(s) {
  const rows=filteredTransactions(s);
  s.offset=Math.min(s.offset,Math.max(0,Math.floor((rows.length-1)/25)*25));
  const visible=rows.slice(s.offset,s.offset+25);
  return `${transactionRows(visible,s)}<div class="pagination"><span>${rows.length?`${s.offset+1}–${Math.min(s.offset+25,rows.length)} of ${rows.length}`:'0'} transactions</span><div><button class="button secondary" data-action="page-prev" ${s.offset===0?'disabled':''}>Previous</button><button class="button secondary" data-action="page-next" ${s.offset+25>=rows.length?'disabled':''}>Next</button></div></div>`;
}
function transactions(s) {
  return `<section class="panel"><div class="panel-heading"><div><h2>Your transaction history</h2><p>${monthLabel(s.month)} · ${s.currency}</p></div>${button('csv','Export CSV','secondary','download')}</div><div class="filters"><label class="search-field">${icon('search')}<input id="search" type="search" placeholder="Search transactions…" aria-label="Search transactions" value="${escape(s.search)}" /></label><label><span class="sr-only">Transaction type</span><select id="type-filter">${[['all','All types'],['expense','Expenses'],['income','Income']].map(([v,l])=>`<option value="${v}" ${s.filter===v?'selected':''}>${l}</option>`).join('')}</select></label><label><span class="sr-only">Category</span><select id="category-filter"><option value="all">All categories</option>${[...new Set([...EXPENSES,...INCOME])].map(c=>`<option ${s.category===c?'selected':''}>${escape(c)}</option>`).join('')}</select></label></div><div id="transaction-results">${transactionResults(s)}</div></section>`;
}
function budgets(s) {
  const sum=summary(s.transactions,s.month),total=s.budgets.filter(b=>b.month===s.month).reduce((a,b)=>a+b.amount,0);
  const totals=categoryTotals(s.transactions,s.month), unbudgeted=Object.keys(totals).filter(c=>!s.budgets.some(b=>b.month===s.month&&b.category===c));
  return `<section class="budget-summary"><div>${icon('target')}<p>YOUR MONTHLY PLAN</p><h2>${money(total,s.currency)}</h2><span>Total category limits · ${monthLabel(s.month)}</span></div><div><p>Spent so far</p><strong>${money(sum.expenses,s.currency)}</strong></div><div><p>${total-sum.expenses<0?'Above total budget':'Remaining'}</p><strong>${money(Math.abs(total-sum.expenses),s.currency)}</strong></div>${button('budget-edit','Edit budgets','primary','edit')}</section><section class="panel"><div class="panel-heading"><div><h2>Category budgets</h2><p>Limits apply only to ${monthLabel(s.month)}. Copy them forward when you’re ready.</p></div>${button('budget-copy','Copy previous month','secondary')}</div>${budgetBars(s)}${unbudgeted.length?`<div class="panel-note">${icon('wallet')}Spending without a category limit: ${unbudgeted.map(escape).join(', ')}. These expenses still count toward your total budget.</div>`:''}</section>`;
}
function reports(s) {
  const months=Array.from({length:6},(_,i)=>shiftMonth(s.month,i-5)), sums=months.map(m=>summary(s.transactions,m)),max=Math.max(1,...sums.flatMap(r=>[r.income,r.expenses]));
  const current=summary(s.transactions,s.month),days=new Date(Number(s.month.slice(0,4)),Number(s.month.slice(5)),0).getDate();
  return `<div class="report-highlights"><div><span>Average expense / calendar day</span><strong>${money(Math.round(current.expenses/days),s.currency)}</strong></div><div><span>Monthly savings rate</span><strong>${current.income?`${Math.round(current.net/current.income*100)}%`:'—'}</strong></div><div><span>Largest spending category</span><strong>${escape(Object.entries(categoryTotals(s.transactions,s.month)).sort((a,b)=>b[1]-a[1])[0]?.[0] || '—')}</strong></div></div><section class="panel"><div class="panel-heading"><div><h2>Income & expenses</h2><p>Six months ending ${monthLabel(s.month)}</p></div><div class="chart-key"><span><i class="key-income"></i>Income</span><span><i class="key-expense"></i>Expenses</span></div></div><div class="bar-chart" role="img" aria-label="Six-month income and expenses chart; exact values in the table below.">${months.map((m,i)=>`<div class="chart-column"><div class="bar-pair"><div class="bar bar-income" style="height:${sums[i].income/max*100}%" title="Income: ${money(sums[i].income,s.currency)}"></div><div class="bar bar-expense" style="height:${sums[i].expenses/max*100}%" title="Expenses: ${money(sums[i].expenses,s.currency)}"></div></div><span>${monthLabel(m,true)}</span></div>`).join('')}</div><div class="table-scroll"><table><thead><tr><th>Month</th><th class="align-right">Income</th><th class="align-right">Expenses</th><th class="align-right">Money left</th></tr></thead><tbody>${months.map((m,i)=>`<tr><td>${monthLabel(m,true)}</td><td class="align-right positive">${money(sums[i].income,s.currency)}</td><td class="align-right">${money(sums[i].expenses,s.currency)}</td><td class="align-right amount ${sums[i].net<0?'negative':''}">${money(sums[i].net,s.currency)}</td></tr>`).join('')}</tbody></table></div></section><section class="panel report-breakdown"><div class="panel-heading"><div><h2>${monthLabel(s.month)} breakdown</h2><p>Every category, at a glance</p></div></div>${spending(s)}</section>`;
}
function settings(s) {
  return `<div class="settings-grid"><section class="panel"><div class="panel-heading"><div><h2>Your workspace</h2><p>Personal preferences & account</p></div>${icon('settings')}</div><div class="settings-body"><label class="field">Display currency<select id="currency">${['CAD','USD','PHP','EUR','GBP','AUD','INR'].map(c=>`<option ${s.currency===c?'selected':''}>${c}</option>`).join('')}</select><small>Applies to every record. Changing this relabels amounts; it does not convert currencies.</small></label><div class="setting-divider"></div><h3>${s.demo?'Try your own workspace':escape(s.user?.email)}</h3><p>${s.demo?'Sign in to keep your records and use them across devices. Demo data stays separate.':'Your records are stored in your account. Other users have separate workspaces.'}</p>${s.demo?button('login','Sign in / create account','primary'):button('logout','Sign out','secondary','logout')}</div></section><section class="panel"><div class="panel-heading"><div><h2>Your data, with you</h2><p>Back up, export, or restore</p></div>${icon('download')}</div><div class="settings-body"><h3>Download a complete backup</h3><p>Includes all transactions, budgets, and your currency. Keep this file somewhere private.</p>${button('backup','Download backup','secondary','download')}<div class="setting-divider"></div><h3>Restore a backup</h3><p>Replace this workspace’s records with a Pocketwise backup. You’ll review the file before confirming.</p><label class="button secondary file-button">${icon('up')}Choose backup file<input type="file" id="restore-file" accept=".json,application/json" /></label><div class="setting-divider"></div><h3>Spreadsheet export</h3><p>Download every transaction as a CSV file.</p>${button('csv-all','Export all transactions','secondary','list')}</div></section></div><div class="panel-note">${icon('cloud')}${s.demo?'Demo changes are temporary. Real accounts require the Supabase setup described in README.md.':'Records refresh when you return to the app and every 30 seconds. An internet connection is needed to save changes.'}</div>`;
}
export function modal(title,content) { return `<div class="dialog-heading"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></div>${content}`; }
export function transactionForm(s,r) {
  const type=r?.type || 'expense';
  return modal(r?'Edit transaction':'Add transaction',`<form id="transaction-form"><input type="hidden" name="id" value="${escape(r?.id || '')}" /><div class="type-toggle">${['expense','income'].map(t=>`<label><input type="radio" name="type" value="${t}" ${type===t?'checked':''} /><span>${icon(t==='income'?'down':'up')}${t==='income'?'Income':'Expense'}</span></label>`).join('')}</div><label class="field amount-field">Amount (${s.currency})<input name="amount" type="text" inputmode="decimal" placeholder="0.00" required autocomplete="off" value="${r?(r.amount/100).toFixed(2):''}" /></label><div class="form-grid"><label class="field">Category<select name="category">${(type==='expense'?EXPENSES:INCOME).map(c=>`<option ${r?.category===c?'selected':''}>${escape(c)}</option>`).join('')}</select></label><label class="field">Account<select name="account">${ACCOUNTS.map(c=>`<option ${r?.account===c?'selected':''}>${c}</option>`).join('')}</select></label></div><label class="field">Date<input type="date" name="date" min="1900-01-01" max="2200-12-31" required value="${r?.date || s.entryDate}" /></label><label class="field">Note <span class="muted">(optional)</span><input name="note" maxlength="240" placeholder="What was this for?" value="${escape(r?.note || '')}" /></label><p class="form-error" role="alert"></p><div class="dialog-actions">${r?`<button type="button" class="button danger-text" data-action="delete" data-id="${escape(r.id)}">Delete transaction</button>`:'<span></span>'}<button class="button primary" type="submit">${r?'Save changes':'Add transaction'}</button></div></form>`);
}
